# Setup
title: Filip Ruzicka
tagline: Evolutionary genetics
paginate: 1
baseurl: ""
permalink: pretty

#Add navigation bar
pages_list:
  Home: '/'
  Bio: '/bio'
  Research: '/research'
  Publications & Code: '/publications'
  Contact: '/contact'


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

slideShow:
  - /assets/DTP_photo.jpg
  - /assets/DTP_photo_small.png

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Filip Ruzicka
  email: filip_ruzicka@hotmail.fr

# Custom vars
version: 3.0.0
